##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors.
##
## See MIT LICENSE file in the root directory.
##
## For more about publishing, see: https://dart.dev/tools/pub/automated-publishing
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: Prepare version

## -----------------------------------------------------------------------------

on:
  push:
    branches:
      - main

## -----------------------------------------------------------------------------

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch dev_package_workflow
        run: rm -rf .github && git clone https://github.com/robmllze/pub.dev_package_workflow.git .github

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.2

      - name: Format Dart code
        run: dart format .

      - name: Apply Dart fixes
        run: dart fix --apply

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //')
          echo "Extracted version: $VERSION"
          echo "extracted_version=$VERSION" >> $GITHUB_ENV

      - name: Get commit messages
        id: get_commits
        run: |
          COMMIT_MESSAGES=$(git log --format=%B -n 1 HEAD)
          echo "messages=${COMMIT_MESSAGES}" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        run: |
          RELEASE_NOTES="${{ env.messages }}"
          dart run .github/scripts/update_changelog.dart "${{ env.extracted_version }}" "$RELEASE_NOTES"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Prepare version ${{ env.extracted_version }}" || echo "No changes to commit"
          git push
